create table if not exists public.user_navigation (
  user_id uuid primary key references auth.users (id) on delete cascade,
  navigation jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.user_navigation enable row level security;

drop policy if exists "Users can view own navigation" on public.user_navigation;
create policy "Users can view own navigation"
on public.user_navigation
for select
using (auth.uid() = user_id);

drop policy if exists "Users can insert own navigation" on public.user_navigation;
create policy "Users can insert own navigation"
on public.user_navigation
for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can update own navigation" on public.user_navigation;
create policy "Users can update own navigation"
on public.user_navigation
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create table if not exists public.site_admins (
  user_id uuid primary key references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.site_admins enable row level security;

drop policy if exists "Users can view own admin row" on public.site_admins;
create policy "Users can view own admin row"
on public.site_admins
for select
using (auth.uid() = user_id);

create table if not exists public.site_announcements (
  id bigint generated by default as identity primary key,
  title text not null default '公告',
  content text not null default '',
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.site_announcements enable row level security;

drop policy if exists "Public can view published announcements" on public.site_announcements;
create policy "Public can view published announcements"
on public.site_announcements
for select
using (is_published = true);

drop policy if exists "Admins can insert announcements" on public.site_announcements;
create policy "Admins can insert announcements"
on public.site_announcements
for insert
to authenticated
with check (
  exists (
    select 1
    from public.site_admins
    where site_admins.user_id = auth.uid()
  )
);

drop policy if exists "Admins can update announcements" on public.site_announcements;
create policy "Admins can update announcements"
on public.site_announcements
for update
to authenticated
using (
  exists (
    select 1
    from public.site_admins
    where site_admins.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.site_admins
    where site_admins.user_id = auth.uid()
  )
);
